[
  { :year => "2000", :artist => "Destinys Child",
    :track => "Independent Women Part I", :genre => "Rock",
    :date_entered => "9/23/2000", :date_peaked => "11/18/2000",
    :week_one => "78", :week_two => "63", :week_three => "49", :week_four => "33", :week_five => "23",
    :week_six => "15", :week_seven => "7", :week_eight => "5", :week_nine => "1", :week_ten => "1" },
  { :year => "2000", :artist => "Santana",
    :track => "Maria, Maria", :genre => "Rock",
    :date_entered => "2/12/2000", :date_peaked => "4/8/2000",
    :week_one => "15", :week_two => "8", :week_three => "6", :week_four => "5", :week_five => "2",
    :week_six => "3", :week_seven => "2", :week_eight => "2", :week_nine => "1", :week_ten => "1" },
  { :year => "2000", :artist => "Savage Garden",
    :track => "I Knew I Loved You", :genre => "Rock",
    :date_entered => "10/23/1999", :date_peaked => "1/29/2000",
    :week_one => "71", :week_two => "48", :week_three => "43", :week_four => "31", :week_five => "20",
    :week_six => "13", :week_seven => "7", :week_eight => "6", :week_nine => "4", :week_ten => "4" },
  { :year => "2000", :artist => "Madonna",
    :track => "Music", :genre => "Rock",
    :date_entered => "8/12/2000", :date_peaked => "9/16/2000",
    :week_one => "41", :week_two => "23", :week_three => "18", :week_four => "14", :week_five => "2",
    :week_six => "1", :week_seven => "1", :week_eight => "1", :week_nine => "1", :week_ten => "2" },
  { :year => "2000", :artist => "Aguilera, Christina",
    :track => "Come On Over Baby (All I Want Is You)", :genre => "Rock",
    :date_entered => "8/5/2000", :date_peaked => "10/14/2000",
    :week_one => "57", :week_two => "47", :week_three => "45", :week_four => "29", :week_five => "23",
    :week_six => "18", :week_seven => "11", :week_eight => "9", :week_nine => "9", :week_ten => "11" },
  { :year => "2000", :artist => "Janet",
    :track => "Doesn't Really Matter", :genre => "Rock",
    :date_entered => "6/17/2000", :date_peaked => "8/26/2000",
    :week_one => "59", :week_two => "52", :week_three => "43", :week_four => "30", :week_five => "29",
    :week_six => "22", :week_seven => "15", :week_eight => "10", :week_nine => "10", :week_ten => "5" },
  { :year => "2000", :artist => "Destinys Child",
    :track => "Say My Name", :genre => "Rock",
    :date_entered => "12/25/1999", :date_peaked => "3/18/2000",
    :week_one => "83", :week_two => "83", :week_three => "44", :week_four => "38", :week_five => "16",
    :week_six => "13", :week_seven => "16", :week_eight => "16", :week_nine => "16", :week_ten => "18" },
  { :year => "2000", :artist => "Iglesias, Enrique",
    :track => "Be With You", :genre => "Latin",
    :date_entered => "4/1/2000", :date_peaked => "6/24/2000",
    :week_one => "63", :week_two => "45", :week_three => "34", :week_four => "23", :week_five => "17",
    :week_six => "12", :week_seven => "9", :week_eight => "8", :week_nine => "8", :week_ten => "6" },
  { :year => "2000", :artist => "Sisqo",
    :track => "Incomplete", :genre => "Rock",
    :date_entered => "6/24/2000", :date_peaked => "8/12/2000",
    :week_one => "77", :week_two => "66", :week_three => "61", :week_four => "61", :week_five => "61",
    :week_six => "55", :week_seven => "2", :week_eight => "1", :week_nine => "1", :week_ten => "2" },
  { :year => "2000", :artist => "Lonestar",
    :track => "Amazed", :genre => "Country",
    :date_entered => "6/5/1999", :date_peaked => "3/4/2000",
    :week_one => "81", :week_two => "54", :week_three => "44", :week_four => "39", :week_five => "38",
    :week_six => "33", :week_seven => "29", :week_eight => "29", :week_nine => "32", :week_ten => "27" },
  { :year => "2000", :artist => "N'Sync",
    :track => "It's Gonna Be Me", :genre => "Rock",
    :date_entered => "5/6/2000", :date_peaked => "7/29/2000",
    :week_one => "82", :week_two => "70", :week_three => "51", :week_four => "39", :week_five => "26",
    :week_six => "19", :week_seven => "15", :week_eight => "9", :week_nine => "7", :week_ten => "7" },
  { :year => "2000", :artist => "Aguilera, Christina",
    :track => "What A Girl Wants", :genre => "Rock",
    :date_entered => "11/27/1999", :date_peaked => "1/15/2000",
    :week_one => "71", :week_two => "51", :week_three => "28", :week_four => "18", :week_five => "13",
    :week_six => "13", :week_seven => "11", :week_eight => "1", :week_nine => "1", :week_ten => "2" },
  { :year => "2000", :artist => "Vertical Horizon",
    :track => "Everything You Want", :genre => "Rock",
    :date_entered => "1/22/2000", :date_peaked => "7/15/2000",
    :week_one => "70", :week_two => "61", :week_three => "53", :week_four => "46", :week_five => "40",
    :week_six => "33", :week_seven => "31", :week_eight => "26", :week_nine => "22", :week_ten => "19" },
  { :year => "2000", :artist => "Creed",
    :track => "With Arms Wide Open", :genre => "Rock",
    :date_entered => "5/13/2000", :date_peaked => "11/11/2000",
    :week_one => "84", :week_two => "78", :week_three => "76", :week_four => "74", :week_five => "70",
    :week_six => "68", :week_seven => "74", :week_eight => "75", :week_nine => "69", :week_ten => "74" },
  { :year => "2000", :artist => "Aaliyah",
    :track => "Try Again", :genre => "Rock",
    :date_entered => "3/18/2000", :date_peaked => "6/17/2000",
    :week_one => "59", :week_two => "53", :week_three => "38", :week_four => "28", :week_five => "21",
    :week_six => "18", :week_seven => "16", :week_eight => "14", :week_nine => "12", :week_ten => "10" },
  { :year => "2000", :artist => "Matchbox Twenty",
    :track => "Bent", :genre => "Rock",
    :date_entered => "4/29/2000", :date_peaked => "7/22/2000",
    :week_one => "60", :week_two => "37", :week_three => "29", :week_four => "24", :week_five => "22",
    :week_six => "21", :week_seven => "18", :week_eight => "16", :week_nine => "13", :week_ten => "12" },
  { :year => "2000", :artist => "Carey, Mariah",
    :track => "Thank God I Found You", :genre => "Rock",
    :date_entered => "12/11/1999", :date_peaked => "2/19/2000",
    :week_one => "82", :week_two => "68", :week_three => "50", :week_four => "50", :week_five => "41",
    :week_six => "37", :week_seven => "26", :week_eight => "22", :week_nine => "22", :week_ten => "2" },
  { :year => "2000", :artist => "Hill, Faith",
    :track => "Breathe", :genre => "Rap",
    :date_entered => "11/6/1999", :date_peaked => "4/22/2000",
    :week_one => "81", :week_two => "68", :week_three => "62", :week_four => "51", :week_five => "42",
    :week_six => "35", :week_seven => "28", :week_eight => "28", :week_nine => "28", :week_ten => "43" },
  { :year => "2000", :artist => "Mya",
    :track => "Case Of The Ex (Whatcha Gonna Do)", :genre => "Rock",
    :date_entered => "8/19/2000", :date_peaked => "12/2/2000",
    :week_one => "72", :week_two => "57", :week_three => "52", :week_four => "47", :week_five => "42",
    :week_six => "31", :week_seven => "24", :week_eight => "18", :week_nine => "17", :week_ten => "17" },
  { :year => "2000", :artist => "Dream",
    :track => "He Loves U Not", :genre => "Rock",
    :date_entered => "9/30/2000", :date_peaked => "12/30/2000",
    :week_one => "99", :week_two => "92", :week_three => "81", :week_four => "59", :week_five => "47",
    :week_six => "42", :week_seven => "32", :week_eight => "27", :week_nine => "18", :week_ten => "18" },
  { :year => "2000", :artist => "Braxton, Toni",
    :track => "He Wasn't Man Enough", :genre => "Rock",
    :date_entered => "3/18/2000", :date_peaked => "5/6/2000",
    :week_one => "63", :week_two => "55", :week_three => "48", :week_four => "39", :week_five => "35",
    :week_six => "24", :week_seven => "3", :week_eight => "2", :week_nine => "2", :week_ten => "4" },
  { :year => "2000", :artist => "Anthony, Marc",
    :track => "You Sang To Me", :genre => "Latin",
    :date_entered => "2/26/2000", :date_peaked => "6/3/2000",
    :week_one => "77", :week_two => "54", :week_three => "50", :week_four => "43", :week_five => "30",
    :week_six => "27", :week_seven => "21", :week_eight => "18", :week_nine => "15", :week_ten => "13" },
  { :year => "2000", :artist => "98 Degrees",
    :track => "Give Me Just One Night (Una Noche)", :genre => "Rock",
    :date_entered => "8/19/2000", :date_peaked => "9/30/2000",
    :week_one => "51", :week_two => "39", :week_three => "34", :week_four => "26", :week_five => "26",
    :week_six => "19", :week_seven => "2", :week_eight => "2", :week_nine => "3", :week_ten => "6" },
  { :year => "2000", :artist => "Destiny's Child",
    :track => "Jumpin' Jumpin'", :genre => "Rock",
    :date_entered => "5/13/2000", :date_peaked => "8/19/2000",
    :week_one => "74", :week_two => "71", :week_three => "65", :week_four => "62", :week_five => "57",
    :week_six => "50", :week_seven => "40", :week_eight => "37", :week_nine => "22", :week_ten => "18" },
  { :year => "2000", :artist => "3 Doors Down",
    :track => "Kryptonite", :genre => "Rock",
    :date_entered => "4/8/2000", :date_peaked => "11/11/2000",
    :week_one => "81", :week_two => "70", :week_three => "68", :week_four => "67", :week_five => "66",
    :week_six => "57", :week_seven => "54", :week_eight => "53", :week_nine => "51", :week_ten => "51" },
  { :year => "2000", :artist => "Sisqo",
    :track => "Thong Song", :genre => "Rock",
    :date_entered => "1/29/2000", :date_peaked => "5/20/2000",
    :week_one => "74", :week_two => "63", :week_three => "35", :week_four => "26", :week_five => "26",
    :week_six => "23", :week_seven => "20", :week_eight => "16", :week_nine => "13", :week_ten => "10" },
  { :year => "2000", :artist => "Aguilera, Christina",
    :track => "I Turn To You", :genre => "Rock",
    :date_entered => "4/15/2000", :date_peaked => "7/1/2000",
    :week_one => "50", :week_two => "39", :week_three => "30", :week_four => "28", :week_five => "21",
    :week_six => "19", :week_seven => "20", :week_eight => "17", :week_nine => "17", :week_ten => "17" },
  { :year => "2000", :artist => "Houston, Whitney",
    :track => "My Love Is Your Love", :genre => "Rock",
    :date_entered => "9/4/1999", :date_peaked => "1/8/2000",
    :week_one => "81", :week_two => "68", :week_three => "44", :week_four => "16", :week_five => "11",
    :week_six => "9", :week_seven => "8", :week_eight => "7", :week_nine => "8", :week_ten => "7" },
  { :year => "2000", :artist => "Joe",
    :track => "I Wanna Know", :genre => "Rock",
    :date_entered => "1/1/2000", :date_peaked => "7/1/2000",
    :week_one => "94", :week_two => "86", :week_three => "69", :week_four => "50", :week_five => "41",
    :week_six => "33", :week_seven => "32", :week_eight => "28", :week_nine => "28", :week_ten => "27" },
].map do |r|
  r[:date_entered] = Date.strptime(r[:date_entered], '%m/%d/%Y')
  r[:date_peaked] = Date.strptime(r[:date_peaked], '%m/%d/%Y')

  Billboard.create(r)
end
